### ISSUE TITLE
Bug: deadline job trace-schedule errors while job is running

### ISSUE THREAD

**Issue by joel-wong-aws** [aws-deadline/deadline-cloud#524]
### Describe the bug

When running `deadline job trace-schedule` on a currently running job, I received the following error:

```
Getting the job...
Getting all the sessions for the job...
Getting all the session actions for the job...
Getting all the steps and tasks for the job...  [####################################]  100%
Processing the trace data...
The AWS Deadline Cloud CLI encountered the following exception:
'endedAt'
Traceback (most recent call last):
  File "C:\Users\test\Documents\GitHub\deadline-cloud\.venv\Lib\site-packages\deadline\client\cli\_common.py", line 54, in wraps
    func(*args, **kwargs)
  File "C:\Users\test\Documents\GitHub\deadline-cloud\.venv\Lib\site-packages\deadline\client\cli\_groups\job_group.py", line 885, in job_trace_schedule
    "ts": time_int(session["endedAt"]),
```

### Expected Behaviour

`deadline job trace-schedule` is only intended to only run for completed, successful jobs. We should document the help text to clarify this and also improve error handling to be more clear about the reason for the failure.

### Current Behaviour

An error occurred.

### Reproduction Steps

Submit a job. While the job is running, run `deadline job trace-schedule`

### Environment

At minimum:
1. Operating system: (e.g. Windows Server 2022; Amazon Linux 2023; etc.): Windows 10 22H2
2. Output of `python3 --version`: `Python 3.12.7`
3. Output of `deadline --version`: 0.49.2
4. If this is from a version installed by the Deadline Cloud Submitter installer, then what version of the submitter installer? N/A

Please share other details about your environment that you think might be relevant to reproducing the bug.

**Comment by lucaseck** [comment]
Adding to this as well that if you run the command before the job has started you'll get a similar error of:
```
The AWS Deadline Cloud CLI encountered the following exception:
'startedAt'
Traceback (most recent call last):
  File "client\cli\_common.py", line 55, in wraps
    func(*args, **kwargs)
  File "client\cli\_groups\job_group.py", line 817, in job_trace_schedule
    started_at = job["startedAt"]
KeyError: 'startedAt'

```
